name: Trabalho Integrador Parte 1 - Pipeline Segura

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write
  security-events: write
  packages: write

jobs:
  scan_build:
    name: Build da Imagem
    runs-on: ubuntu-latest
    steps:
      - name: Checar codigo
        uses: actions/checkout@v2
      - name: Construir imagem local
        run: docker build -t pipeline-segura:latest .
      - name: Salvar imagem como arquivo TAR
        run: docker save -o pipeline-segura.tar pipeline-segura:latest
      - name: Upload temporario da imagem
        uses: actions/upload-artifact@v4
        with:
          name: tmp-pipeline-segura
          path: pipeline-segura.tar
          retention-days: 1
  execucao_dockle:
    name: Execucao do Dockle
    runs-on: ubuntu-latest
    needs: scan_build
    steps:
      - name: realizado download do arquivo .tar da imagem
        uses: actions/download-artifact@v4
        with:
          name: tmp-pipeline-segura
      - name: Carregar imagem no docker local
        run: docker load -i pipeline-segura.tar
      - name: executando o dockle
        uses: goodwithtech/dockle-action@main
        with:
          image: pipeline-segura:latest
          format: 'list'
          exit-code: '1'
          exit-level: 'fatal'
  execucao_trivy:
    name: Execucao do Trivy
    runs-on: ubuntu-latest
    needs: execucao_dockle
    steps:
      - name: realizado download do arquivo .tar da image
        uses: actions/download-artifact@v4
        with:
          name: tmp-pipeline-segura
      - name: Carregar imagem no docker local
        run: docker load -i pipeline-segura.tar
      - name: Scan com Trivy para analise CVE
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'pipeline-segura:latest'
          format: 'table'
          scanners: 'vuln,secret'
          exit-code: '1'
          severity: 'CRITICAL'
  assinatura_imagem:
    name: Publicacao e assinatura da Imagem
    runs-on: ubuntu-latest
    needs: execucao_trivy
    steps:
      - name: Checar codigo
        uses: actions/checkout@v2
      - name: Assinatura imagem - instalacao cosign
        uses: sigstore/cosign-installer@v4.0.0
      - name: Login Github container registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Informacoes tag da imagem
        id: docker_meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ghcr.io/${{ github.actor }}/pipeline-segura
          tags: |
            type: sha,format=long
            type: raw,value=latest
      - name: Build e push oficial para o GHCR
        uses: docker/build-push-action@v6.18.0
        id: build_and_push
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Assinatura e verificacao da imagem com github OIDC Token
        env:
          DIGEST: ${{ steps.build_and_push.outputs.digest }}
        run: |
          USER_LOWER=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_BASE="ghcr.io/${USER_LOWER}/pipeline-segura"
          cosign sign --yes "${IMAGE_BASE}@${DIGEST}"
          cosign verify "${IMAGE_BASE}@${DIGEST}" \
          --certificate-identity=https://github.com/${{ github.actor }}/aula_atq_def_containers/.github/workflows/pipeline_segura.yml@refs/heads/main \
          --certificate-oidc-issuer=https://token.actions.githubusercontent.com
  gerar_sbom:
    name: Gerar imagem publicada
    runs-on: ubuntu-latest
    needs: assinatura_imagem
    steps:
      - name: Formatar nome do usuario para minusculo
        id: string_format
        run: |
          USER_LOWER=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          echo "user_lower=${USER_LOWER}" >> $GITHUB_OUTPUT
      - name: Gerar SBOM com trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'image'
          image-ref: 'ghcr.io/${{ steps.string_format.outputs.user_lower }}/pipeline-segura:latest'
          format: 'cyclonedx'
          output: 'resultado.sbom.json'
      - name: UPload relatorio trivy como artefato
        uses: actions/upload-artifact@v4
        with:
          name: resultado-sbom-trivy
          path: resultado.sbom.json
          retention-days: 20